version: "3.3"

volumes:
  postgres_local:

services:

  postgres:
    image: postgres:11.0-alpine
    environment:
      - POSTGRES_USER=postgresuser
      - POSTGRES_PASSWORD=postgrespw
      - PGPASSWORD=postgrespw
      - TZ=UTC
      - PGTZ=UTC
    volumes:
      - postgres_local:/var/lib/postgresql/data
      - ./_infrastructure/postgre/init/:/docker-entrypoint-initdb.d/
    ports:
      - 25432:5432

  pubsub:
    image: singularities/pubsub-emulator
    environment:
      - PUBSUB_PROJECT_ID=my-development
      - PUBSUB_LISTEN_ADDRESS=0.0.0.0:8432
    ports:
      - "8432:8432"
